import { z } from "zod";
import { sessionSchema } from "./schema";

// Published schedule snapshot: https://reactalicante.es/#schedule (2026-09-23).
// Topics are editorial workshop tags. Lightning times are the shared block.
// See docs/agenda-data.md for provenance and missing fields.
export const sessions = z.array(sessionSchema).parse([
  {
    id: "24-glenn-reyes",
    date: "2026-09-24",
    title: "Building Generative UI with MCP in React",
    speaker: "Glenn Reyes",
    startTime: "09:00",
    endTime: "13:00",
    room: "1.2",
    topic: "ai",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Glenn Reyes.",
  },
  {
    id: "24-dominik-dorfmeister",
    date: "2026-09-24",
    title: "React Query - Beyond the Basics",
    speaker: "Dominik Dorfmeister",
    startTime: "09:00",
    endTime: "13:00",
    room: "1.3",
    topic: "react",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Dominik Dorfmeister.",
  },
  {
    id: "24-evangelia-mitsopoulou",
    date: "2026-09-24",
    title: "Build Your Agentic Workflow: Markdown-Driven AI for Real Projects",
    speaker: "Evangelia Mitsopoulou",
    startTime: "09:00",
    endTime: "13:00",
    room: "1.4",
    topic: "ai",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Evangelia Mitsopoulou.",
  },
  {
    id: "24-matheus-albuquerque",
    date: "2026-09-24",
    title: "Compilers & Static Analysis for JavaScript Developers",
    speaker: "Matheus Albuquerque",
    startTime: "09:00",
    endTime: "13:00",
    room: "2.2",
    topic: "tooling",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Matheus Albuquerque.",
  },
  {
    id: "24-devlin-duldulao",
    date: "2026-09-24",
    title: "10x React Development with TanStack Query, HeyAPI, and AI Copilots",
    speaker: "Devlin Duldulao",
    startTime: "09:00",
    endTime: "13:00",
    room: "2.3",
    topic: "ai",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Devlin Duldulao.",
  },
  {
    id: "24-kathleen-mcmahon",
    date: "2026-09-24",
    title: "Design System Test Kitchen! Recipes for AI-Ready Components",
    speaker: "Kathleen McMahon",
    startTime: "14:15",
    endTime: "18:15",
    room: "1.2",
    topic: "design",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Kathleen McMahon.",
  },
  {
    id: "24-flavio-corpa",
    date: "2026-09-24",
    title: "Functional programming in TypeScript",
    speaker: "Flavio Corpa",
    startTime: "14:15",
    endTime: "18:15",
    room: "1.3",
    topic: "typescript",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Flavio Corpa.",
  },
  {
    id: "24-faris-aziz",
    date: "2026-09-24",
    title:
      "Real-World React: Designing Frontend Architectures That Survive Production",
    speaker: "Faris Aziz",
    startTime: "14:15",
    endTime: "18:15",
    room: "1.4",
    topic: "react",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Faris Aziz.",
  },
  {
    id: "24-shivay-lamba",
    date: "2026-09-24",
    title: "Building AI-Powered React Apps with TanStack AI",
    speaker: "Shivay Lamba",
    startTime: "14:15",
    endTime: "18:15",
    room: "2.2",
    topic: "ai",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Shivay Lamba.",
  },
  {
    id: "24-lukasz-nowak",
    date: "2026-09-24",
    title: "Test your frontends the bulletproof way",
    speaker: "Łukasz Nowak",
    startTime: "14:15",
    endTime: "18:15",
    room: "2.3",
    topic: "testing",
    kind: "workshop",
    timing: "session",
    description: "Workshop by Łukasz Nowak.",
  },
  {
    id: "25-daniel-afonso",
    date: "2026-09-25",
    title: "React-Driven Development: Career Lessons from the Framework Wars",
    speaker: "Daniel Afonso",
    startTime: "09:00",
    endTime: "09:30",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Daniel Afonso.",
  },
  {
    id: "25-matteo-collina",
    date: "2026-09-25",
    title: "The New Node.js: Built-in Batteries and the Road Ahead",
    speaker: "Matteo Collina",
    startTime: "09:30",
    endTime: "10:00",
    room: null,
    topic: "tooling",
    kind: "talk",
    timing: "session",
    description: "Talk by Matteo Collina.",
  },
  {
    id: "25-kateryna-porshnieva",
    date: "2026-09-25",
    title: "Making your codebase AI-ready",
    speaker: "Kateryna Porshnieva",
    startTime: "10:00",
    endTime: "10:30",
    room: null,
    topic: "ai",
    kind: "talk",
    timing: "session",
    description: "Talk by Kateryna Porshnieva.",
  },
  {
    id: "25-joel-arvidsson",
    date: "2026-09-25",
    title: "Native o’clock: time to use the platform",
    speaker: "Joel Arvidsson",
    startTime: "11:00",
    endTime: "11:30",
    room: null,
    topic: "native",
    kind: "talk",
    timing: "session",
    description: "Talk by Joel Arvidsson.",
  },
  {
    id: "25-aurora-scharff",
    date: "2026-09-25",
    title: "What RSCs can do in Next.js today",
    speaker: "Aurora Scharff",
    startTime: "11:30",
    endTime: "12:00",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Aurora Scharff.",
  },
  {
    id: "25-mattia-manzati",
    date: "2026-09-25",
    title: "Your simple frontend shares backend challenges",
    speaker: "Mattia Manzati",
    startTime: "12:00",
    endTime: "12:30",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Mattia Manzati.",
  },
  {
    id: "25-sara-vieira",
    date: "2026-09-25",
    title: "Breakout Session: Building 3D Games in React",
    speaker: "Sara Vieira",
    startTime: "12:30",
    endTime: "13:00",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Sara Vieira.",
  },
  {
    id: "25-lukasz-nowak",
    date: "2026-09-25",
    title: "D[JS]",
    speaker: "Łukasz Nowak",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "tooling",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-milica-draca",
    date: "2026-09-25",
    title: "Building Schema-Driven Forms in React",
    speaker: "Milica Drača",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-krzysztof-kowalczyk",
    date: "2026-09-25",
    title: "Improving frontend developer productivity in large React codebases",
    speaker: "Krzysztof Kowalczyk",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "tooling",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-eduardo-aparicio-cardenes",
    date: "2026-09-25",
    title:
      "From Isolation to Acceleration: Building the fastest payment platform on an iFrame",
    speaker: "Eduardo Aparicio Cardenes",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-sujit-pradhan",
    date: "2026-09-25",
    title: "React Compiler: Goodbye useMemo? Rethinking React Performance",
    speaker: "Sujit Pradhan",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-marcel-kalveram",
    date: "2026-09-25",
    title: "Monoliths Work: Until They Don’t",
    speaker: "Marcel Kalveram",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-oana-gabriela-stroe",
    date: "2026-09-25",
    title: "Redrawing the line between engineering and design",
    speaker: "Oana Gabriela Stroe",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "design",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-jakub-tkacz",
    date: "2026-09-25",
    title: "How Expo Observe can help you improve your app",
    speaker: "Jakub Tkacz",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "native",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "25-forbes-lindesay",
    date: "2026-09-25",
    title: "Fun with streams",
    speaker: "Forbes Lindesay",
    startTime: "16:40",
    endTime: "17:10",
    room: null,
    topic: "tooling",
    kind: "talk",
    timing: "session",
    description: "Talk by Forbes Lindesay.",
  },
  {
    id: "25-erik-rasmussen",
    date: "2026-09-25",
    title: "Ripple: the Good Parts of React, Svelte, and Solid",
    speaker: "Erik Rasmussen",
    startTime: "17:10",
    endTime: "17:40",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Erik Rasmussen.",
  },
  {
    id: "25-kevin-maes",
    date: "2026-09-25",
    title: "Beyond Client-Side State: React Meets Durable Execution",
    speaker: "Kevin Maes",
    startTime: "17:40",
    endTime: "18:10",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Kevin Maes.",
  },
  {
    id: "26-dominik-dorfmeister",
    date: "2026-09-26",
    title:
      "Dead Code Shouldn’t Exist: How We Removed 28k Lines of Code, One Knip at a Time",
    speaker: "Dominik Dorfmeister",
    startTime: "09:00",
    endTime: "09:30",
    room: null,
    topic: "tooling",
    kind: "talk",
    timing: "session",
    description: "Talk by Dominik Dorfmeister.",
  },
  {
    id: "26-ankita-kulkarni",
    date: "2026-09-26",
    title:
      "Build. Scale. Teach: Architecting and Scaling a Production-Ready Modern Course Platform",
    speaker: "Ankita Kulkarni",
    startTime: "09:30",
    endTime: "10:00",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Ankita Kulkarni.",
  },
  {
    id: "26-mark-erikson",
    date: "2026-09-26",
    title:
      "How I Made Immer Twice as Fast: Performance Optimization in Practice",
    speaker: "Mark Erikson",
    startTime: "10:00",
    endTime: "10:30",
    room: null,
    topic: "tooling",
    kind: "talk",
    timing: "session",
    description: "Talk by Mark Erikson.",
  },
  {
    id: "26-matheus-albuquerque",
    date: "2026-09-26",
    title: "Visual Continuity on the Web: My Journey With View Transitions",
    speaker: "Matheus Albuquerque",
    startTime: "11:00",
    endTime: "11:30",
    room: null,
    topic: "design",
    kind: "talk",
    timing: "session",
    description: "Talk by Matheus Albuquerque.",
  },
  {
    id: "26-faris-aziz",
    date: "2026-09-26",
    title: "Building Resilient UIs with React",
    speaker: "Faris Aziz",
    startTime: "11:30",
    endTime: "12:00",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Faris Aziz.",
  },
  {
    id: "26-aileen-villanueva-lecuona",
    date: "2026-09-26",
    title: "My AI-Driven React Workflow: Building Faster with Agent",
    speaker: "Aileen Villanueva Lecuona",
    startTime: "12:00",
    endTime: "12:30",
    room: null,
    topic: "ai",
    kind: "talk",
    timing: "session",
    description: "Talk by Aileen Villanueva Lecuona.",
  },
  {
    id: "26-ferran-negre",
    date: "2026-09-26",
    title: "React Native is Native: Back at React Alicante, 8 Years Later",
    speaker: "Ferran Negre",
    startTime: "12:30",
    endTime: "13:00",
    room: null,
    topic: "native",
    kind: "talk",
    timing: "session",
    description: "Talk by Ferran Negre.",
  },
  {
    id: "26-devlin-duldulao",
    date: "2026-09-26",
    title: "Redwood SDK: React Server Components on the Edge, Simplified",
    speaker: "Devlin Duldulao",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-hayk-yaghubyan",
    date: "2026-09-26",
    title:
      "The React White Screen of Death: Detection, Recovery, and UX Strategies",
    speaker: "Hayk Yaghubyan",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-milica-aleksic",
    date: "2026-09-26",
    title:
      "Multiple Apps, Millions of Users: Scaling React Native in Production",
    speaker: "Milica Aleksic",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "native",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-cesar-alberca",
    date: "2026-09-26",
    title:
      "Software Craftless: Writing Code That Would Make a Goat Vomit (React Edition)",
    speaker: "César Alberca",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "react",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-shivay-lamba",
    date: "2026-09-26",
    title: "Building AI-Powered React Apps with TanStack AI",
    speaker: "Shivay Lamba",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "ai",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-nestor-lopez",
    date: "2026-09-26",
    title:
      "Rspack and Module Federation: The modern path to distributed microfrontends",
    speaker: "Néstor López",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "tooling",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-evangelia-mitsopoulou",
    date: "2026-09-26",
    title:
      "Beyond Linting: Building an AI Code Reviewer Grounded in Architectural Mental Models",
    speaker: "Evangelia Mitsopoulou",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "ai",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-christopher-buecheler",
    date: "2026-09-26",
    title: "You Are a Customer Success Engineer (or at least you should be!)",
    speaker: "Christopher Buecheler",
    startTime: "14:25",
    endTime: "16:10",
    room: null,
    topic: "other",
    kind: "lightning",
    timing: "block",
    description:
      "Part of the 14:25–16:10 lightning block. Individual time is not published.",
  },
  {
    id: "26-violina-popova",
    date: "2026-09-26",
    title: "Controlling Async Chaos in React with Effect-TS",
    speaker: "Violina Popova",
    startTime: "16:40",
    endTime: "17:10",
    room: null,
    topic: "typescript",
    kind: "talk",
    timing: "session",
    description: "Talk by Violina Popova.",
  },
  {
    id: "26-aris-markogiannakis",
    date: "2026-09-26",
    title: "React Security Odyssey: Sailing with CSP to Ithaca",
    speaker: "Aris Markogiannakis",
    startTime: "17:10",
    endTime: "17:40",
    room: null,
    topic: "react",
    kind: "talk",
    timing: "session",
    description: "Talk by Aris Markogiannakis.",
  },
  {
    id: "26-kitze",
    date: "2026-09-26",
    title: "Title not announced",
    speaker: "Kitze",
    startTime: "17:40",
    endTime: "18:10",
    room: null,
    topic: "other",
    kind: "talk",
    timing: "session",
    description: "Title not yet published by the conference.",
  },
]);
