import { z } from "zod";
import { sessionSchema } from "./schema";

// All sessions are fictional. This is not the React Alicante schedule.
export const sessions = z.array(sessionSchema).parse([
  {
    id: "react-state",
    title: "State that stays understandable",
    startTime: "09:00",
    endTime: "09:45",
    room: "A",
    level: "beginner",
    topic: "react",
    description: "Model a screen without duplicating state.",
  },
  {
    id: "ts-boundaries",
    title: "TypeScript at the boundary",
    startTime: "09:00",
    endTime: "09:45",
    room: "B",
    level: "intermediate",
    topic: "typescript",
    description: "Validate untrusted inputs and narrow unknown values.",
  },
  {
    id: "react-effects",
    title: "Effects without surprises",
    startTime: "10:00",
    endTime: "10:45",
    room: "A",
    level: "intermediate",
    topic: "react",
    description: "Synchronize with external systems and clean up correctly.",
  },
  {
    id: "accessible-forms",
    title: "Forms everyone can use",
    startTime: "10:00",
    endTime: "10:45",
    room: "B",
    level: "beginner",
    topic: "accessibility",
    description: "Labels, focus, validation and useful errors.",
  },
  {
    id: "ai-tools",
    title: "Tools a model can use",
    startTime: "11:00",
    endTime: "11:45",
    room: "A",
    level: "beginner",
    topic: "ai",
    description: "Design tool names and schemas that explain their purpose.",
  },
  {
    id: "testing-ui",
    title: "Test the user journey",
    startTime: "11:00",
    endTime: "11:45",
    room: "B",
    level: "intermediate",
    topic: "testing",
    description: "Choose assertions that capture observable behavior.",
  },
  {
    id: "react-patterns",
    title: "React patterns for adaptive views",
    startTime: "13:00",
    endTime: "13:45",
    room: "A",
    level: "intermediate",
    topic: "react",
    description: "Render trusted components from a typed view model.",
  },
  {
    id: "ai-mcp",
    title: "MCP Apps in practice",
    startTime: "13:00",
    endTime: "13:45",
    room: "B",
    level: "intermediate",
    topic: "ai",
    description: "Connect tools, resources and an interactive interface.",
  },
  {
    id: "react-performance",
    title: "A faster React screen",
    startTime: "14:00",
    endTime: "14:45",
    room: "A",
    level: "advanced",
    topic: "react",
    description: "Measure render work before reaching for optimization.",
  },
  {
    id: "ts-unions",
    title: "Model views with unions",
    startTime: "14:00",
    endTime: "14:45",
    room: "B",
    level: "intermediate",
    topic: "typescript",
    description: "Make invalid presentation states hard to represent.",
  },
  {
    id: "react-design",
    title: "A small React design system",
    startTime: "15:00",
    endTime: "15:45",
    room: "A",
    level: "beginner",
    topic: "react",
    description: "Build reusable components with explicit variants.",
  },
  {
    id: "testing-contracts",
    title: "Contracts across an iframe",
    startTime: "15:00",
    endTime: "15:45",
    room: "B",
    level: "advanced",
    topic: "testing",
    description: "Test data and behavior on both sides of the bridge.",
  },
]);
